services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: blog-mysql-container
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - blog-mysql-data:/var/lib/mysql
  #     - ./mysql-init:/docker-entrypoint-initdb.d
  #   networks:
  #     - blog-network
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "mysqladmin",
  #         "ping",
  #         "-h",
  #         "localhost",
  #         "-p${MYSQL_ROOT_PASSWORD}",
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend
    container_name: backend-container
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${BACKEND_PORT}:5000"
    networks:
      - blog-network
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - blog-network

# volumes:
#   blog-mysql-data:

networks:
  blog-network:
    driver: bridge
